version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - django_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=110102ee
    ports:
      - "5433:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_USER=postgres
      - DB_PASSWORD=110102ee
    depends_on:
      - db

volumes:
  django_postgres:
