# Generated by Django 5.2.1 on 2025-06-20 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tarefa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 13, 50, 36, 620890)),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
