# Generated by Django 5.2.1 on 2025-06-20 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tarefa_create_tarefa_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 17, 3, 55, 768852)),
        ),
    ]
