# Generated by Django 5.2.1 on 2025-06-20 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_tarefa_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='finished',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
